[pytest]
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')
    skipif: marks tests that should be skipped conditionally
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
